<section class="admin__page-section order-delivery-note">
    <div class="admin__page-section-title">
        <span class="title"><?= $block->escapeHtml(__('Delivery Note')) ?></span>
    </div>
    <div class="admin__page-section-content">
        <div class="admin__page-section-item order-delivery-note">
            <div><?= $block->escapeHtml($block->getDeliveryNote()) ?></div>
        </div>
    </div>
</section>